build:
  artifactId: '@project.artifactId@'
  timestamp: '@timestamp@'
  version: '@project.version@'
server:
  max-http-header-size: 1048576
  servlet-path: /Service/*
  port: 8080
#  tomcat:
#    max-connections: 3000
#    max-http-post-size: 1048576
#    max-threads: 1000
spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  cache:
    cache-names: token
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=3600s
  data:
    mongodb:
      database: ${EPCIS_DB_NAME:epcis} 
      ssl: ${EPCIS_DB_SSL:false}
      uri: ${EPCIS_DB_URL:mongodb://localhost:27017/} 
  identity-service:
    url: http://${IDENTITY_SRV_HOST:nimble-staging.salzburgresearch.at}:${IDENTITY_SRV_PORT:80}/identity      
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
epcis:
  capture:
    verification: true   

 